# Generated by Django 6.1.1 on 2026-10-03 14:23

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scope", models.CharField(db_index=True, max_length=200)),
                ("endpoint", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=100)),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["scope", "endpoint"], name="django_idem_scope_0f43f8_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "endpoint", "key"), name="django_idem_unique_key"
                    )
                ],
            },
        ),
    ]
